Add IPv6 support in cloudflare

diff --git a/cloudflare-ddns b/cloudflare-ddns
--- a/cloudflare-ddns
+++ b/cloudflare-ddns
@@ -18,15 +18,39 @@ API="https://api.cloudflare.com/client/v4"
 LOG_FILE=/var/log/me.renfrew.dnsUpdate
 LOG_DIR=$(dirname $LOG_FILE)
 
+IPv4_PATTERN='^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
+IPv6_PATTERN='^([0-9a-fA-F]{0,4}:){1,7}[0-9a-fA-F]{0,4}$'
+
+# Check if the required parameters are passed
+if [ "$#" -ne 4 ]; then
+  echo "Wrong number of parameters passed"
+  echo "Usage:"
+  echo "    $0 <ACCESS_TOKEN> <DOMAIN> <SUBDOMAIN> <TTL>"
+  exit
+fi
+
+ACCESS_TOKEN="$1"
+DOMAIN="$2"
+SUBDOMAIN="$3"
+TTL="$4"
+
+HOSTNAME="$SUBDOMAIN.$DOMAIN"
+
+# Create log files if they don't exist and have the permission to write
 if [[ ! -e "$LOG_FILE.log" && ! -e "$LOG_FILE.err" && -w "$LOG_DIR" ]]; then
     touch $LOG_FILE.log
     touch $LOG_FILE.err
 fi
 
+# Redirect stderr to log files if they have the permission to write
 if [[ -w "$LOG_FILE.log" && -w "$LOG_FILE.err" ]]; then
   exec 2> >(tee -a $LOG_FILE.err $LOG_FILE.log)
+else
+  echo "Warning: Cannot write to log files in $LOG_DIR, please check the permissions"
 fi
 
+# Function to log to console and log file
+# Usage: logger_own <LEVEL> <MESSAGE>
 logger_own() {
   # Print to console
   echo $2
@@ -37,35 +61,27 @@ logger_own() {
   fi
 }
 
-if [ "$#" -ne 4 ]; then
-  echo "Wrong number of parameters passed"
-  echo "Usage:"
-  echo "$0 <ACCESS_TOKEN> <DOMAIN> <SUBDOMAIN> <TTL>"
-  exit
-fi
+# Get the current external IP of the host
+# Usage: get_external_ip <4|6>
+get_external_ip() {
+  EXTERNAL_IP=$(dig @ns1.google.com -$1 o-o.myaddr.l.google.com TXT +short | jq '.' --raw-output)
+  logger_own INFO "Current external IPv$1 is \"$EXTERNAL_IP\""
+}
 
-ACCESS_TOKEN="$1"
-DOMAIN="$2"
-SUBDOMAIN="$3"
-TTL="$4"
+# Get the current IP resolved by the DNS
+# Usage: get_current_ip <A|AAAA>
+get_current_ip() {
+  local TYPE=$([[ $1 == "AAAA" ]] && echo "28" || echo "1")
+  CURRENT_IP=$(curl --silent \
+    -H 'accept: application/dns-json' \
+    "https://cloudflare-dns.com/dns-query?name=$HOSTNAME&type=$1" |
+    jq -c ".Answer[]? | select(.type == $TYPE) | .data" --raw-output
+  )
 
-IP_PATTERN='^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
+  logger_own INFO "Current $HOSTNAME type $1 DNS record is \"$CURRENT_IP\""
+}
 
-EXTERNAL_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
-if [[ ! $EXTERNAL_IP =~ $IP_PATTERN ]]; then
-  logger_own ERROR "There was a problem resolving the external IP, response was \"$EXTERNAL_IP\""
-  exit
-fi
-logger_own DEBUG  "Current external IP is $EXTERNAL_IP"
-
-HOSTNAME="$SUBDOMAIN.$DOMAIN"
-CURRENT_IP=$(
-  curl --silent -H 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=$HOSTNAME&type=A" |
-  jq -c '.Answer[]? | select(.type == 1) | .data' --raw-output
-)
-logger_own DEBUG "Current $HOSTNAME DNS record is \"$CURRENT_IP\""
-
-if [[ "$CURRENT_IP" != "$EXTERNAL_IP" ]]; then
+get_dns_records() {
   DNS_ZONES_RESPONSE=$(curl -s "$API/zones?status=active" --header "Authorization: Bearer $ACCESS_TOKEN" --header "Content-Type:application/json")
   if [[ $(echo $DNS_ZONES_RESPONSE | jq ".success" --raw-output) != "true" ]]; then
     logger_own ERROR "There was a problem fetching the DNS zones, response code was $(echo $DNS_ZONES_RESPONSE | jq '.errors[0] | .code' --raw-output)"
@@ -78,11 +94,36 @@ if [[ "$CURRENT_IP" != "$EXTERNAL_IP" ]]; then
     logger_own ERROR "There was a problem fetching the DNS records, response code was $(echo $DNS_RECORDS_RESPONSE | jq '.errors[0] | .code' --raw-output)"
     exit
   fi
+}
 
-  RECORD=$(echo $DNS_RECORDS_RESPONSE | jq ".result[]  | select(.name == \"$HOSTNAME\")" --raw-output)
-  BODY=$(jq -n --arg hostname "$HOSTNAME" --arg externalIp "$EXTERNAL_IP" --arg ttl $TTL '
+# Update the IP if it has changed
+# Usage: update_ip <4|6>
+update_ip() {
+  local TYPE=$([[ $1 == "6" ]] && echo "AAAA" || echo "A")
+
+  get_current_ip $TYPE
+  get_external_ip $1
+  if [[ ! $EXTERNAL_IP =~ $IPv4_PATTERN && ! $EXTERNAL_IP =~ $IPv6_PATTERN ]]; then
+    logger_own ERROR "There was a problem resolving the external type $TYPE IP, response was \"$EXTERNAL_IP\""
+    return
+  fi
+
+  if [[ "$CURRENT_IP" == "$EXTERNAL_IP" ]]; then
+    logger_own INFO "$HOSTNAME $TYPE record is up-to-date with the current external IP $EXTERNAL_IP"
+    return
+  fi
+
+  logger_own INFO "Updating $HOSTNAME $TYPE record to $EXTERNAL_IP with a TTL of $TTL"
+
+  if [[ -z $DNS_RECORDS_RESPONSE ]]; then
+    get_dns_records
+  fi
+  
+
+  RECORD=$(echo $DNS_RECORDS_RESPONSE | jq ".result[]  | select(.name == \"$HOSTNAME\" and .type ==\"$TYPE\")" --raw-output)
+  BODY=$(jq -n --arg type "$TYPE" --arg hostname "$HOSTNAME" --arg externalIp "$EXTERNAL_IP" --arg ttl $TTL '
   {
-    "type": "A",
+    "type": $type,
     "name": $hostname,
     "content": $externalIp,
     "ttl": $ttl|tonumber
@@ -121,10 +162,13 @@ if [[ "$CURRENT_IP" != "$EXTERNAL_IP" ]]; then
   NEW_RECORD_VALUE=$(echo $RESPONSE | jq ".result | .content" --raw-output)
   NEW_RECORD_TTL=$(echo $RESPONSE | jq ".result | .ttl" --raw-output)
 
-  if [[ $NEW_RECORD_TYPE != "A" ]] || [[ $NEW_RECORD_HOSTNAME != $HOSTNAME ]] || [[ $NEW_RECORD_VALUE != $EXTERNAL_IP ]] || [[ $NEW_RECORD_TTL != $TTL ]]; then
+  if [[ $NEW_RECORD_TYPE != $TYPE ]] || [[ $NEW_RECORD_HOSTNAME != $HOSTNAME ]] || [[ $NEW_RECORD_VALUE != $EXTERNAL_IP ]] || [[ $NEW_RECORD_TTL != $TTL ]]; then
     logger_own ERROR "There was a problem creating the new entry, some values did not match"
     exit
   fi
 
-  logger_own INFO "Successfully updated $HOSTNAME to $EXTERNAL_IP with a TTL of $TTL"
-fi
+  logger_own INFO "Successfully updated $HOSTNAME $TYPE record to $EXTERNAL_IP with a TTL of $TTL"
+}
+
+update_ip 4
+update_ip 6
